matthewbub/calendar-widgets

README.md
lib/calendar/README.md

Resolve issue #9. I added the website link to both README.md files but not the third one since I couldn't find it.

Add website link to README.md files.

---

workspaces/docs/docs/introduction.md

Just changed the links from hard coded domain to just use the url hierarchy
solved the issue #72 no opens in the same tab

solved:fix docs homepage - it should use relative paths not absolute #72

---

workspaces/calendar-widgets/.npmignore

Ignore the src directory in the .npmignore file
Added src to .npmignore

solved:#issue80

---

workspaces/calendar-widgets/package.json

remove the start script from Calendar-Widgets package #88 
Removed the start script

solved:issue#88

---

workspaces/tests/test/formatDate.test.js

Removed the failing test suite as a temporary solution to allow other devs to contribute

#89 temp fix: rm failing test suites to allow

---

workspaces/calendar-widgets/package.json
workspaces/calendar-widgets/pnpm-lock.yaml
workspaces/calendar-widgets/rollup.config.dev.js
workspaces/calendar-widgets/rollup.config.prod.js

Setup Rollup with separate configuration files for production and development builds

#102 Setup Rollup with separate configuration files for production and development builds

---

workspaces/calendar-widgets/package.json
workspaces/calendar-widgets/pnpm-lock.yaml
workspaces/calendar-widgets/rollup.config.dev.js
workspaces/calendar-widgets/src/components/Hello.tsx
workspaces/calendar-widgets/src/constants.ts
workspaces/calendar-widgets/src/helpers/listLocalizedMonths.ts
workspaces/calendar-widgets/tsconfig.json
workspaces/docs/docs/changelog.md

- Added React to Rollup configuration for module bundling
- Added new method `listLocalizedMonths`

#121 Add React to Rollup configuration for module bundling

---

package.json
workspaces/calendar-widgets/package.json

I have included MIT license information package.json file. Please review and advise.
Thank you,

#125 included MIT license in package.json

---

workspaces/docs/sidebars.js

#133 As assigned: I successfully fixed the broken link issue on the sidebar.js file, ensuring that Docusaurus can now build successfully. I thoroughly tested the fix and confirmed that the build process is now successful without any issues.

Fixed Broken Link

---

workspaces/calendar-widgets/.eslintrc.cjs
workspaces/calendar-widgets/src/components/Calendar/Calendar.types.ts
workspaces/calendar-widgets/src/components/Calendar/index.tsx
workspaces/calendar-widgets/src/components/Draggable/Draggable.styles.css
workspaces/calendar-widgets/src/components/Draggable/index.tsx
workspaces/calendar-widgets/src/constants.ts
workspaces/calendar-widgets/src/helpers/listLocalizedWeekDays.ts
workspaces/calendar-widgets/src/stories/Calendar.stories.tsx
workspaces/calendar-widgets/src/stories/Draggable.stories.tsx
workspaces/docs/docs/changelog.md

both of these are mvps, neither are ready for use 🙂 Sneaking them into the codebase to avoid potential headaches with #150 
If you want a sneak peek, there's available for preview in `workspaces/calendar-widgets` via the `pnpm run storybook` command

#115 MVP Calendar & Draggable components

---

workspaces/calendar-widgets/.npmignore
workspaces/docs/docusaurus.config.js
workspaces/docs/src/components/ArgDescriptor/ArgDescriptor.jsx
workspaces/docs/src/components/ArgDescriptor/styles.module.css

Title: Modified "workspaces/docs/src/components/ArgDescriptor/styles.module.css"
Description:
I've made some changes to the mentioned file to fit the ask. 
Changes Made:
- Added bottom margin of 10px to .arg-description--name and .arg-description--type
- Added bottom margin, border bottom and padding bottom as mentioned for .description
Please review and let me know if there are any further changes or suggestions. I'm open to feedback and willing to make additional updates as needed. Thanks for considering this pull request!

Updated styling for ArgDescriptor component in workspaces/tests #146

---

@types/calendar-widgets/index.d.ts
docs/docs/introduction.md
docs/docusaurus.config.js
docs/package.json
docs/pnpm-lock.yaml
docs/src/components/EndlessCards/EndlessCards.tsx
docs/src/components/EndlessCards/EndlessCards.types.ts
docs/src/components/EndlessCards/index.ts
docs/src/components/index.ts
docs/src/components/types.ts
docs/src/constants/landing/EndlessCards.constants.ts
docs/src/constants/landing/index.ts
docs/src/css/tailwind.css
docs/src/pages/index.tsx
docs/tailwind.config.js
docs/tsconfig.json
package.json
rollup.config.js
src/react/Calendar/Calendar.tsx
src/react/Calendar/Calendar.types.ts
src/react/DraggableDay/DraggableDay.tsx
src/react/DraggableDay/Draggables.styles.css

#187 Fix dist package publishing error

---

.github/ISSUE_TEMPLATE/bug.yml

#202 Bug Report - Github Issues Template

---

.github/ISSUE_TEMPLATE/bug.yml

#202 add checkboxes to bug report template

---

.github/ISSUE_TEMPLATE/bug.yml

#202 relocate comment in bug report template

---

.github/ISSUE_TEMPLATE/bug.yml

Still troubleshooting #202 
#202

#202 wrap `name` field in string

---

.github/ISSUE_TEMPLATE/config.yml

blank issues disabled from .github/ISSUE_TEMPLATE/config.yml, ISSUE #203

blank issues disabled from config

---

.github/ISSUE_TEMPLATE/bug.yml

#268 Fix - allow user input in bug template

---

.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature.yml
.github/PULL_REQUEST_TEMPLATE.md

#93 add feature template, support links

---

LICENSE

first time making a pull request, hope I didn't mess up

updated license per instructions
